<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="6" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="HELLOSuite" duration-ms="54993" started-at="2019-07-07T11:41:34Z" finished-at="2019-07-07T11:42:29Z">
    <groups>
    </groups>
    <test name="NewTest" duration-ms="54993" started-at="2019-07-07T11:41:34Z" finished-at="2019-07-07T11:42:29Z">
      <class name="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases">
        <test-method status="PASS" signature="init1()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="init1" is-config="true" duration-ms="10212" started-at="2019-07-07T11:41:34Z" finished-at="2019-07-07T11:41:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init1 -->
        <test-method status="PASS" signature="Test1()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="Test1" duration-ms="14" started-at="2019-07-07T11:41:44Z" finished-at="2019-07-07T11:41:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="teardown" is-config="true" duration-ms="740" started-at="2019-07-07T11:41:44Z" finished-at="2019-07-07T11:41:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="init1()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="init1" is-config="true" duration-ms="8237" started-at="2019-07-07T11:41:45Z" finished-at="2019-07-07T11:41:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init1 -->
        <test-method status="PASS" signature="Test2()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="Test2" duration-ms="7" started-at="2019-07-07T11:41:53Z" finished-at="2019-07-07T11:41:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="teardown" is-config="true" duration-ms="726" started-at="2019-07-07T11:41:53Z" finished-at="2019-07-07T11:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="init1()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="init1" is-config="true" duration-ms="8449" started-at="2019-07-07T11:41:54Z" finished-at="2019-07-07T11:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init1 -->
        <test-method status="SKIP" signature="Test3()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="Test3" duration-ms="4" started-at="2019-07-07T11:42:02Z" finished-at="2019-07-07T11:42:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases.Test3(ScreenshotFailedTestCases.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="teardown" is-config="true" duration-ms="733" started-at="2019-07-07T11:42:02Z" finished-at="2019-07-07T11:42:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="init1()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="init1" is-config="true" duration-ms="7700" started-at="2019-07-07T11:42:03Z" finished-at="2019-07-07T11:42:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init1 -->
        <test-method status="SKIP" signature="Test3()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="Test3" duration-ms="13" started-at="2019-07-07T11:42:11Z" finished-at="2019-07-07T11:42:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases.Test3(ScreenshotFailedTestCases.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="teardown" is-config="true" duration-ms="727" started-at="2019-07-07T11:42:11Z" finished-at="2019-07-07T11:42:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="init1()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="init1" is-config="true" duration-ms="7078" started-at="2019-07-07T11:42:12Z" finished-at="2019-07-07T11:42:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init1 -->
        <test-method status="SKIP" signature="Test3()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="Test3" duration-ms="3" started-at="2019-07-07T11:42:19Z" finished-at="2019-07-07T11:42:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases.Test3(ScreenshotFailedTestCases.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="teardown" is-config="true" duration-ms="781" started-at="2019-07-07T11:42:19Z" finished-at="2019-07-07T11:42:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="init1()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="init1" is-config="true" duration-ms="7766" started-at="2019-07-07T11:42:19Z" finished-at="2019-07-07T11:42:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init1 -->
        <test-method status="FAIL" signature="Test3()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="Test3" duration-ms="2" started-at="2019-07-07T11:42:27Z" finished-at="2019-07-07T11:42:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases.Test3(ScreenshotFailedTestCases.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases@77caeb3e]" name="teardown" is-config="true" duration-ms="721" started-at="2019-07-07T11:42:28Z" finished-at="2019-07-07T11:42:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases -->
    </test> <!-- NewTest -->
  </suite> <!-- HELLOSuite -->
</testng-results>
