<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="admin-PC" name="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases" tests="6" failures="1" timestamp="07 Jul 2019 11:42:29 GMT" time="53.913" errors="0">
  <testcase name="Test3" time="8.431" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="10.948" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test2" time="7.811" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases"/>
  <testcase name="Test1" time="8.561" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases"/>
  <testcase name="Test3" time="9.202" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="8.960" classname="com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases.Test3(ScreenshotFailedTestCases.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test3 -->
</testsuite> <!-- com.qa.retryfailedtestcases.Rahul.ScreenshotFailedTestCases -->
